[package]
# TODO: Project Information
name = "example_project"
version = "0.0.0"
description = "Example Description"
authors = ["DanMizu"]
license = "GPL-3.0-or-later"
repository = "https://github.com/Dan-Mizu/Phaser3-Tauri-Template"
# Leave this alone, as it references the Tauri edition, and has nothing to do with your project.
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-log = "2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

